Public Class Sentencias
    Public Const BUSCAR_CLIENTES = "SP_INVEN_CLIENTE_CONSULTAR"
    Public Const CARGAR_CLIENTES = "SP_INVEN_CLIENTE_CARGAR"
    Public Const CLIENTE_FACTURA_CARGAR = "SP_CLIENTE_FACTURA_CARGAR"
End Class
