Public Class Sentencias
    Public Const BUSCAR_CLIENTES = "SP_INVEN_CLIENTE_CONSULTAR"
    Public Const CARGAR_CLIENTES = "SP_INVEN_CLIENTE_CARGAR"
    Public Const CLIENTE_FACTURA_CARGAR = "SP_CLIENTE_FACTURA_CARGAR"
    Public Const PRODUCTOS_SERVICIO_FACTURA_BUSCAR = "SP_PRODUCTOS_SERVICIO_FACTURA_BUSCAR"
    Public Const PRODUCTOS_SERVICIO_FACTURA_CARGAR = "SP_PRODUCTOS_SERVICIO_FACTURA_CARGAR"
    Public Const BUSCAR_FACTURAS = "SP_FACTURAS_BUSCAR"
End Class
