Public Class Titulo
    Public Const BODEGA = ""
    Public Const BUSQUEDA_INVENTARIO = "Busqueda de Inventario"
    Public Const BUSQUEDA_COMPRA = "Busqueda de Compra"
    Public Const BUSQUEDA_PRODUCTO = "Busqueda de producto"
    Public Const BUSQUEDA_SUCURSAL = "Busqueda de Sucursales"
    Public Const BUSQUEDA_EMPLEADO = "Busqueda de Empleado"
    Public Const BUSQUEDA_PERSONA = "Busqueda de persona"
    Public Const BUSQUEDA_PROVEEDOR = "Busqueda de Proveedor"
    Public Const BUSQUEDA_SERVICIO = "Busqueda de servicio"
    Public Const BUSQUEDA_LISTA_PRECIO = "Busqueda de lista precio"
    Public Const BUSQUEDA_FACTURA = "Busqueda de Facturas"
    Public Const BUSQUEDA_EXISTENCIA = "Existencia de producto"
    Public Const BUSQUEDA_GASTO_SERVICIO = "Busqueda de gastos"
End Class
