Public Class TitulosForm
    Public Const BUSQUEDA_AJUSTE = "Busqueda de Ajustes"
    Public Const BUSQUEDA_LIQUIDACIONES = "Busqueda de Liquidaciones"
    Public Const BUSQUEDA_NOTAS_CREDITO = "Busqueda de Notas de Glosa"
    Public Const BUSQUEDA_GLOSAS = "Busqueda de Notificaciones de Glosa"
    Public Const BUSQUEDA_FACTURAS = "Busqueda de Facturas"
    Public Const BUSQUEDA_FACTURA_DE_VENTAS = "Busqueda de Facturas de Ventas"
    Public Const BUSQUEDA_PERIODICIDAD_INSUMOS = "Busqueda de Periodicidad Insumos"
    Public Const BUSQUEDA_ESTADO_ATENCION = "Busqueda de estado atención"
    Public Const BUSQUEDA_MANUAL = "Busqueda de Manuales"
    Public Const BUSQUEDA_CAUSA_EXTERNA = "Busqueda de Causa Externa"
    Public Const BUSQUEDA_MUNICIPIOS = "Busquedas de Municipios"
    Public Const BUSQUEDA_TRANSPORTADORAS = "Busqueda de Transportadoras"
    Public Const BUSQUEDA_DOCUMENTOS_CONTABLES = "Busqueda de Documentos Contables"
    Public Const BUSQUEDA_PROGRAMACION_PROVEEDOR = "Busqueda de Programacion de Pago"
    Public Const BUSQUEDA_CONFIGURACION_AUDITORIA = "Busqueda de configuraciones"
    Public Const BUSQUEDA_CLIENTES = "Busqueda de clientes"
    Public Const BUSQUEDA_INSUMOS = "Busqueda de insumos"
    Public Const BUSQUEDA_PROCEDIMIENTOS_CUPS = "Busqueda de procedimientos cups"
    Public Const BUSQUEDA_EPS = "Busqueda de EPS"
    Public Const BUSQUEDA_TARIFAS = "Busqueda de tarifas"
    Public Const BUSQUEDA_RESOLUCION = "Busqueda de resoluciones"
    Public Const BUSQUEDA_EMPRESA = "Busqueda de empresas"
    Public Const BUSQUEDA_PACIENTE = "Busqueda de pacientes"
    Public Const BUSQUEDA_CONSOLIDADO_LAB = "Busqueda de consolidado de laboratorio"
    Public Const BUSQUEDA_TRASLADOS = "Busqueda de traslados"
    Public Const BUSQUEDA_PROVEEDOR = "Busqueda de proveedores"
    Public Const BUSQUEDA_PROVEEDOR_LABORATORIO = "Busqueda de proveedores Laboratorio"
    Public Const BUSQUEDA_DIAGNOSTICO_CIE = "Busqueda de diagnósticos"
    Public Const BUSQUEDA_EMPLEADO_HC = "Busqueda de empleados"
    Public Const BUSQUEDA_EQUIVALENCIA = "Busqueda de equivalencias"
    Public Const BUSQUEDA_ADMISION = "Busqueda de Atenciones"
    Public Const BUSQUEDA_EPICRISIS = "Busqueda de epicrisis"
    Public Const BUSQUEDA_LINEA = "Busqueda de linea"
    Public Const BUSQUEDA_GRUPO = "Busqueda de grupo"
    Public Const BUSQUEDA_TERCERO = "Busqueda de tercero"
    Public Const BUSQUEDA_DEPARTAMENTOS_GLOSA = "Busqueda departamentos glosa"
    Public Const BUSQUEDA_VIA_INGRESO = "Busqueda de Via Ingreso"
    Public Const BUSQUEDA_BANCOS = "Busqueda de bancos"
    Public Const BUSQUEDA_NOTA_AUDITORIA = "Busqueda de notas auditoria"
    Public Const BUSQUEDA_AREA_SERVICIO = "Busqueda de área de servicio"
    Public Const BUSQUEDA_PUNTO_SERVICIO = "Busqueda de punto de servicio"
    Public Const BUSQUEDA_MARCAS = "Busqueda de Marca"
    Public Const BUSQUEDA_DEVOLUCION = "Busqueda de Devolucion"
    Public Const BUSQUEDA_MINUTA = "Busqueda de minutas"
    Public Const BUSQUEDA_OTRO_SI = "Busqueda de otro si"
    Public Const BUSQUEDA_PERFIL_USUARIO = "Busqueda de perfil de usuario"
    Public Const BUSQUEDA_ANEXO1 = "Busqueda de Anexo"
    Public Const BUSQUEDA_ANEXO2 = "Busqueda de Anexo2"
    Public Const BUSQUEDA_FARMACOLOGICO = "Busqueda farmacologico"
    Public Const BUSQUEDA_OBSERVACION = "Busqueda observacion"
    Public Const BUSQUEDA_CAMA = "Busqueda cama"
    Public Const BUSQUEDA_CONTRATO = "Busqueda de contratos"
    Public Const BUSQUEDA_CONTRATO_LABORALES = "Busqueda de contratos laborales"
    Public Const BUSQUEDA_CNTT_LBRLS_MINUTAS = "Busqueda de minutas"
    Public Const BUSQUEDA_BAJA_PRODUCTO = "Busqueda baja inventario"
    Public Const BUSQUEDA_SOLICITUD_MEDICAMENTO_NOPOS = "Busqueda de medicamentos NO POS"
    Public Const BUSQUEDA_PRODUCTOS_INDIVIDUAL_CONTEO = "Busqueda de productos"
    Public Const BUSQUEDA_DOCUMENTOS = "Busqueda tipos de documento"
    Public Const BUSQUEDA_PROCEDIMIENTO_TRASLADOS = "Busqueda de procedimientos traslados"
    Public Const BUSQUEDA_CONTEO = "Busqueda Conteo"
    Public Const BUSQUEDA_CUPS = "Busqueda CUPS"
    Public Const BUSQUEDA_SGCUPS = "Busqueda de GRUPOS"
    Public Const BUSQUEDA_SUBGCUPS = " Busqueda de subgrupos"
    Public Const BUSQUEDA_ARTICULO_SOAT = "Busqueda de CAPITULOS"
    Public Const BUSQUEDA_LISTA_PRECIO_MEDICAMENTO = "Busqueda de Listas de precios"
    Public Const BUSQUEDA_DIAGNOSTICOS_ULTIMA_EVO = "Busqueda de Diagnosticos"
    Public Const BUSQUEDA_HORARIO = "Busqueda de horario laboral"
    Public Const BUSQUEDA_DEDUCCION = "Busqueda de deduccion"
    Public Const BUSQUEDA_PUC = "Busqueda Plan Unico de Cuentas"
    Public Const BUSQUEDA_CUENTAS_UCI = "Busqueda Clasificación Cuentas UCI"
    Public Const BUSQUEDA_CUENTAS_PUC = "Busqueda Cuentas PUC"
    Public Const BUSQUEDA_CUENTAS_PUC_RETENCION = "Busqueda Cuentas Retencion e IVA"
    Public Const BUSQUEDA_RETENCION_IVA = "Busqueda Cuentas Retencion e IVA"
    Public Const BUSQUEDA_ESTANCIA = "Busqueda de estancias"
    Public Const BUSQUEDA_ECOCARDIOGRAMA = "Busqueda Ecocardiograma"
    Public Const BUSQUEDA_MED_E_INSUMO_POS = "Busqueda de medicamentos e insumos POS"
    Public Const BUSQUEDA_MEDICAMENTO = "Busqueda de medicamentos"
    Public Const BUSQUEDA_VIA = "Busqueda de Vias"
    Public Const BUSQUEDA_CLIENTES_COTIZACION = "Busqueda Cliente"
    Public Const BUSQUEDA_PRODUCTOS_COTIZACION = "Busqueda Productos"
    Public Const BUSQUEDA_SONDA = "Busqueda Sonda"
    Public Const BUSQUEDA_VENOPUNCION = "Busqueda Venopuncion"
    Public Const BUSQUEDA_COTIZACION = "Busqueda Cotizacion"
    Public Const BUSQUEDA_INDICACION = "Busqueda de Indicaciones"
    Public Const BUSQUEDA_COMIDA = "Busqueda de Comidas"
    Public Const BUSQUEDA_CONFIGURACION_COMIDA = "Busqueda configuración de comida"
    Public Const BUSQUEDA_OXIGENO = "Busqueda de Oxígenos"
    Public Const BUSQUEDA_PARACLINICO = "Busqueda de Paraclínicos"
    Public Const BUSQUEDA_HEMODERIVADO = "Busqueda de Hemoderivados"
    Public Const BUSQUEDA_GLUCOMETRIA = "Busqueda de Glucometrias"
    Public Const BUSQUEDA_PROCEDIMIENTO = "Busqueda de Procedimientos"
    Public Const BUSQUEDA_EVOLUCION = "Busqueda de evoluciones médicas"
    Public Const BUSQUEDA_CAJA_BANCO = "Busqueda de Saldos Iniciales"
    Public Const BUSQUEDA_RECETARIO = "Busqueda recetario"
    Public Const BUSQUEDA_CASO_PROBLEMA = "Busqueda caso problema"
    Public Const BUSQUEDA_CATETER_CENTRAL = "Busqueda de cateter"
    Public Const BUSQUEDA_CATETERISMO = "Busqueda de cateterismo"
    Public Const BUSQUEDA_MEDICAMENTOS_INSUMOS = "Busqueda de Medicamentos e Insumos"
    Public Const BUSQUEDA_PROCEDIMIENTOS_REMISION = "Busqueda de Procedimientos "
    Public Const BUSQUEDA_CURACION = "Busqueda Curacion"
    Public Const BUSQUEDA_REMISION_INVENTARIO = "Busqueda de Remisiones"
    Public Const BUSQUEDA_NUTRICIONAL = "Busqueda Nutricional"
    Public Const BUSQUEDA_EQUIVALENCIA_PEDIDO_SERVICO = "Buscar Equivalencias"
    Public Const BUSQUEDA_PEDIDO_SERVICIO = "Busqueda de Pedidos de Servicio"
    Public Const BUSQUEDA_DESPACHO_PEM = "Busqueda de Despacho PEM"
    Public Const BUSQUEDA_DESPACHO_PEDIDO = "Busqueda de Despachos de Pedido de Servicio"
    Public Const BUSQUEDA_CTC = "Busqueda de Comite Tecnico Cientifico (C.T.C)"
    Public Const BUSQUEDA_BODEGA = "Busqueda de Bodega"
    Public Const BUSQUEDA_PUNTOS_BODEGA = "Busqueda de los puntos de la  Bodega"
    Public Const BUSQUEDA_RESPONSABLE = "Busqueda Responsable"
    Public Const BUSQUEDA_PRESENTACION = "Busqueda de presentaciones"
    Public Const BUSQUEDA_PROFESION = "Busqueda de profesiones"
    Public Const BUSQUEDA_ARL = "Busqueda de ARL"
    Public Const BUSQUEDA_DOCUMENTO = "Busqueda de tipo identificacion"
    Public Const BUSQUEDA_CARGOS = "Busqueda de cargos"
    Public Const BUSQUEDA_PENSION = "Busqueda Pension"
    Public Const BUSQUEDA_OBSERVACIONES = "Busqueda Observaciones"
    Public Const BUSQUEDA_PAIS = "Busqueda de pais"
    Public Const BUSQUEDA_DIAS_VENCIMIENTO = "Busqueda de dias de vencimiento"
    Public Const BUSQUEDA_CUALIDADES = "Busqueda de Cualidades"
    Public Const BUSQUEDA_DEPARTAMENTO = "Busqueda departamento"
    Public Const BUSQUEDA_REGIMEN = "Busqueda de tipo regimen"
    Public Const BUSQUEDA_DESTINO = "Busqueda de destino"
    Public Const BUSQUEDA_CAPITULO_CUPS = "Busqueda de capítulos"
    Public Const BUSQUEDA_CONVERCIONES = "Busqueda de Converciones"
    Public Const BUSQUEDA_INSTITUCION = "Busqueda de instituciones"
    Public Const BUSQUEDA_CAPITULO_CUPS2 = "Busqueda de SECCIONES"
    Public Const BUSQUEDA_ESPECIALIDAD = "Busqueda de especialidad"
    Public Const BUSQUEDA_ESTADOCIVIL = "Busqueda de estado civil"
    Public Const BUSQUEDA_CAJA_COMPENSACION = "Busqueda de caja de compensacion"
    Public Const BUSQUEDA_PLAZOS = "Busqueda de Plazos"
    Public Const BUSQUEDA_ENTREGA = "Busqueda de días Entrega"
    Public Const BUSQUEDA_HEMODIALISIS = "Busqueda de hemodíalisis"
    Public Const BUSQUEDA_CATEGORIAS_CUPS = "Busqueda de categorias"
    Public Const BUSQUEDA_MANUAL_SOAT = "Busqueda de Manual"
    Public Const BUSQUEDA_GRUPO_SOAT = "Busqueda de  Grupos"
    Public Const BUSQUEDA_CAPITULOS_SOAT = "Busqueda de Capitulos"
    Public Const BUSQUEDA_RECEPCION = "Busqueda de Recepción"
    Public Const BUSQUEDA_COMPRA = "Busqueda de Compra"
    Public Const BUSQUEDA_PEDIDO_TRASLADOS = "Busqueda de Pedidos"
    Public Const BUSQUEDA_CIIU = "Busqueda CIIU"
    Public Const BUSQUEDA_JUSTIFICACION = "Busqueda justificacion"
    Public Const BUSQUEDA_BUZON = "Busqueda buzon"
    Public Const BUSQUEDA_TIPO_COMIDA = "Busqueda pedido Comida"
    Public Const BUSQUEDA_ORDEN_COMPRA = "Busqueda de ordenes de compra"
    Public Const BUSQUEDA_CONFIGURACION_CORREO = "Busqueda de correos"
    Public Const BUSQUEDA_PROGRAMACION_ORDEN_COMPRA = "Busqueda de programación de ordenes de compra"
    Public Const BUSQUEDA_COMPROBANTE_CAUSACION = "Busqueda Comprobantes de Causacion"
    Public Const BUSQUEDA_NOTA_PROVEEDOR = "Busqueda Nota Proveedor"
    Public Const BUSQUEDA_NOTA_INTERNA = "Busqueda Nota Interna"
    Public Const BUSQUEDA_OXIGENO_MODO_VENTILACION = "Busqueda Oxigeno"
    Public Const BUSQUEDA_CUENTA_PUC = "Busqueda cuenta"
    Public Const BUSQUEDA_NOTA_CLIENTE = "Busqueda Nota Cliente"
    Public Const BUSQUEDA_COMPROBANTE_EGRESO = "Busqueda egreso"
    Public Const BUSQUEDA_PEDIDO_FARMACIA = "Busqueda Pedido Farmacia"
    Public Const BUSQUEDA_SOLICITUDES = "Busqueda Solicitud Laboratorio"
    Public Const BUSQUEDA_FORMATO_INGRESO = "Busqueda de Formatos de Ingreso"
    Public Const BUSQUEDA_TARIFA_TRIPULACION = "Busqueda Tarifa Tripulacion"
    Public Const BUSQUEDA_MANUAL_TARIFARIO = "Busqueda Manual Tarifario"
    Public Const BUSQUEDA_SALDO_PENDIENTE = "Busqueda saldo pendiente factura"
    Public Const BUSQUEDA_RECAUDO = "Busqueda de recibo caja (Recaudo)"
    Public Const BUSQUEDA_PRODUCTOS = "Busqueda de Producto"
    Public Const BUSQUEDA_CLASE_SOCIAL = "Busqueda de clase social"
    Public Const BUSQUEDA_TIPO_EXAMEN = "Busqueda de Tipos Examenes"
    Public Const BUSQUEDA_OCUPACION = "Busqueda de Ocupaciones"
    Public Const BUSQUEDA_PARAMETRO = "Busqueda de Parametros"
    Public Const BUSQUEDA_TARIFA_CUERPO_MEDICO = "Busqueda Tarifa Medica"
    Public Const BUSQUEDA_CUENTA_COBRO = "Busqueda Cuentas de Cobros"

    'TITULOS DE VENTANAS AMBULANCIA
    Public Const BUSQUEDA_CONTRATO_AM = "Buscar Contrato Ambulancia"
    Public Const BUSQUEDA_ATENCION_AM = "Buscar Atención Ambulancia"
    Public Const BUSQUEDA_REPORTE_INF_AM = "Buscar Reporte Informativo Ambulancia"
    'QUITAR FILAS 
    Public Const QUITAR_FILAS = "Quitar Filas"
    'TITULOS DE VENTANAS EMERGENTES
    Public Const GUARDAR = "GUARDAR"
    Public Const EDITAR = "EDITAR"
    Public Const CANCELAR = "CANCELAR"
    Public Const ANULAR = "ANULAR"
    Public Const DUPLICAR = "DUPLICAR"
    Public Const TRASLADO_PACIENTE = "TRASLADO PACIENTE"
    Public Const SALIR = "SALIR"
    Public Const TERMINAR = "TERMINAR"

    '--------------
    Public Const MANEJO = "MANEJO DEL PACIENTE"
    Public Const DIAGNOTICOS = "DIAGNOSTICO DEL PACIENTE"
    Public Const DIAGNOTICOS_INGRESO = "Diagnosticos Ingreso"
    Public Const DIAGNOTICOS_EGRESO = "Diagnosticos Egreso"

    ' titulos de configuracion
    Public Const TITULO_ESTANCIA = "ESTANCIA"
    Public Const TITULO_TRANSFUSION_SANGUINEA = "TRANSFUSIÓN"
    Public Const TITULO_PARACLINICO = "PARACLINICO"
    Public Const TITULO_QUIRURGICO = "QUIRURGICO"
    'examenes paraclinicos 
    Public Const TITULO_ELECTROLITO = "Electrolito"
    Public Const TITULO_HEMOGRAMA = "Hemograma"
    Public Const TITULO_QUIMICA_SANGUINEA = "Quimica Sanguinea"
    Public Const TITULO_GRUPO_TORCH = "Grupo Torch"
    Public Const TITULO_GASES_ARTERIALES = "Gases Arteriales"
    ' Archivo
    Public Const BUSQUEDA_ESTANTE = "Busqueda de Estante"
    Public Const BUSQUEDA_BLOQUE = "Busqueda de Bloque"
    Public Const BUSQUEDA_FILA = "Busqueda de Fila"
    Public Const BUSQUEDA_FACTURA = "Busqueda de Factura"
    '-------- titulos ecocardiogama
    Public Const TITULO_ECO = "ECOCARDIOGRAMA: HISTORIA CLÍNICA"
    Public Const TITULO_ECO_R = "ECOCARDIOGRAMA: AUDITORÍA MÉDICA"
    Public Const TITULO_ECO_RR = "ECOCARDIOGRAMA: AUDITORÍA FACTURACIÓN"
    '-------- titulos ecocardiogama Estres
    Public Const TITULO_ECO_ESTRES = "PRUEBA DE ESFUERZO: HISTORIA CLÍNICA"
    Public Const TITULO_ECO_ESTRES_R = "PRUEBA DE ESFUERZO:  AUDITORÍA MÉDICA"
    Public Const TITULO_ECO_ESTRES_RR = "PRUEBA DE ESFUERZO: AUDITORÍA FACTURACIÓN"
    '----------  Titulo Informe Qx
    Public Const TITULO_INFORME_QX = "INFORME QUIRURGICO: HISTORIA CLÍNICA"
    Public Const TITULO_INFORME_QX_R = "INFORME QUIRURGICO: AUDITORÍA MÉDICA"
    Public Const TITULO_INFORME_QX_RR = "INFORME QUIRURGICO: AUDITORÍA FACTURACIÓN"
    '.------------------- titulo cateterismo
    Public Const TITULO_INFORME_HEMODINAMIA = "INFORME HEMODINAMIA: HISTORIA CLÍNICA"
    Public Const TITULO_INFORME_HEMODINAMIA_R = "INFORME HEMODINAMIA: AUDITORÍA MÉDICA"
    Public Const TITULO_INFORME_HEMODINAMIA_RR = "INFORME HEMODINAMIA: AUDITORÍA FACTURACIÓN"

    Public Const BUSQUEDA_CONFIGURACION_RIPS = "Busqueda de formato rips"
    Public Const BUSQUEDA_PEMS = "Busqueda PEMS"

    '------hoja de ruta 
    Public Const TITULO_HOJA_RUTA = "HOJA DE RUTA"
    Public Const TITULO_HOJA_RUTA_HC = "HOJA DE RUTA: HÍSTORIA CLINICA"
    Public Const TITULO_HOJA_RUTA_AM = "HOJA DE RUTA: AUDITORÍA MÉDICA"
    Public Const TITULO_HOJA_RUTA_AF = "HOJA DE RUTA: AUDITORÍA FACTURACIÓN"
    Public Const TITULO_HOJA_PROGRAMAR_TAREA = "TAREAS PROGRAMADAS PARA: "
    '---------------------Configuracion Afiliaciòn-------------------------------------------
    Public Const BUSQUEDA_AFILIACION = "Busqueda de afiliados"
    '-------- titulos resultado paraclinicos
    Public Const TITULO_RESULT = "RESULTADO PARACLINICOS: HISTORIA CLÍNICA"
    Public Const TITULO_RESULT_R = "RESULTADO PARACLINICOS: AUDITORÍA MÉDICA"
    Public Const TITULO_RESULT_RR = "RESULTADO PARACLINICOS: AUDITORÍA FACTURACIÓN"
    Public Const TITULO_ARCHIVO = "DOCUMENTACIÓN"

    Public Const TITULO_SOL_MED_NO_POS = "Solicitud de solicitudes NO POS"
    Public Const TITULO_JUSTIFICACION_ANT = "Justificación de Antibióticos"
    Public Const TITULO_INFORME_QUIRURGICO = "Informe Quirúrgico"
    Public Const TITULO_HEMODIALISIS = "Informe Hemodiálisis"
    Public Const TITULO_CATETERISMO = "Solicitud Cateterismo"
    '--------nomina---------------------------
    Public Const BUSQUEDA_NOMINA = "Busqueda Nómina"
    '-------------Examen Laboratorio 
    Public Const EXAMEN_LABORATORIO = "Examen Laboratorio - Historia Clinica"
    Public Const EXAMEN_LABORATORIO_R = "Examen Laboratorio - Auditoria Medica"
    Public Const EXAMEN_LABORATORIO_RR = "Examen Laboratorio - Auditoria Facturación"
    Public Const ATENCION_EXAMEN_LABORATORIO = "Examen Laboratorio - Atencion"
    '--------------Imagenologia 
    Public Const TITULO_IMAGENOLOGIA = "IMAGENOLOGIA: HISTORIA CLÍNICA"
    Public Const TITULO_IMAGENOLOGIA_R = "IMAGENOLOGIA: AUDITORÍA MÉDICA"
    Public Const TITULO_IMAGENOLOGIA_RR = "IMAGENOLOGIA: AUDITORÍA FACTURACIÓN"
    Public Const TITULO_LABORATORIO = "LABORATORIO: SOLICITUDES DE LABORATORIO"
    Public Const TITULO_ESTUDIO = "ESTUDIOS"
    '-----------------------------------------
    Public Const TITULO_EMPLEADO = "Busqueda de empleado"
    '--------------- Perfil Paraclinino
    Public Const BUSQUEDA_PERFIL_PARACLINICO = "Busqueda de Perfiles Paraclinicos"

    '---------------Plantilla informes Especiales
    Public Const BUSQUEDA_PLANTILLA_INFO = "Busquedas de Plantillas de Informes Especiales Configuradas"
    Public Const TITULO_INFORME_PLANTILLA = "Plantilla de Informes Especiales"
End Class

